#!/bin/bash
#SBATCH -N 1 
#SBATCH -n 36 
#SBATCH --ntasks-per-node=36
#SBATCH --ntasks-per-core=1
#SBATCH --mem=30000
#SBATCH --time=1-0:0

module purge
module load intel/18.2 intelmpi/18.2




srun /users/p21006/partage/Software/4_Lammps_withPlumed1906/lammps-master/src/lmp_mpi  -i input.lmp 

