#!/bin/bash

for i in $(seq -w 01  1 10 )
do
	if [ ! -f colvar$i".out" ]; then
		cp model.lmp input.lmp
		tmp=$RANDOM
		sed -i "s/xSeed/$tmp/g"   input.lmp
		lmp_mpi  -i input.lmp 
		mv dump.lammpstrj dump$i".lammpstrj"
		mv colvar.out colvar$i".out"
	fi
done

